[package]
name = "penrose"
version = "0.1.5"
edition = "2018"
authors = ["sminez <innes.andersonmorrison@gmail.com>"]
license = "MIT"
repository = "https://github.com/sminez/penrose"
documentation = "https://docs.rs/penrose"
readme = "README.md"
description = """
A tiling window manager library/WM for X11 in the style of dwm and Xmonad.
"""

[[bin]]
doc = false
name = "penrose"
path = "src/example/main.rs"

[dependencies]
xcb = { version = "0.9.0", features = ["randr"] }
log = "0.4.8"
simplelog = "0.8.0"
