[package]
name = "penrose"
version = "0.1.0"
edition = "2018"
authors = ["sminez <innes.andersonmorrison@gmail.com>"]
license-file = "LICENSE"
repository = "https://github.com/sminez/penrose"
documentation = "https://docs.rs/penrose"
readme = "README.md"
description = """
A tiling window manager library/WM for X11 in the style of dwm.
"""

[[bin]]
doc = false
name = "penrose"
path = "src/penrose.rs"

[dependencies]
xcb = { version = "0.9.0", features = ["randr"] }
