name: dangerjs

on:
  pull_request:
    branches:
      - develop

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  danger:
    name: Run danger.ts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: danger/danger-js@9.1.6
